- id: djlint-django
  name: djLint for Django
  entry: djlint --profile=django
  types_or: [html]
  language: python

- id: djlint-jinja
  name: djLint for Jinja
  entry: djlint --profile=jinja
  types_or: [jinja]
  language: python

- id: djlint-nunjucks
  name: djLint for Nunjucks
  entry: djlint --profile=nunjucks
  types_or: [nunjucks]
  language: python

- id: djlint-handlebars
  name: djLint for Handlebars/Mustache
  entry: djlint --profile=handlebars
  types_or: [handlebars]
  language: python

- id: djlint-golang
  name: djLint for Golang templates
  entry: djlint --profile=golang
  types_or: [gotmpl]
  language: python
